### ISSUE TITLE
Unable to install the latest version easily

### ISSUE THREAD

**Issue by m-rossi** [conda-forge/px-proxy-feedstock#13]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

If i try to install/create an environment with `px-proxy` it tries to install an outdated version `20220127` instead of `0.8.3`

```shell
conda create -n px-proxy px-proxy
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\miniforge\envs\px-proxy

  added / updated specs:
    - px-proxy

The following NEW packages will be INSTALLED:

  bzip2              conda-forge/win-64::bzip2-1.0.8-h8ffe710_4 None
  ca-certificates    conda-forge/win-64::ca-certificates-2022.9.24-h5b45459_0 None
  jaraco.classes     conda-forge/noarch::jaraco.classes-3.2.2-pyhd8ed1ab_0 None
  keyring            conda-forge/win-64::keyring-23.9.3-py310h5588dad_0 None
  libffi             conda-forge/win-64::libffi-3.4.2-h8ffe710_5 None
  libsqlite          conda-forge/win-64::libsqlite-3.39.4-hcfcfb64_0 None
  libzlib            conda-forge/win-64::libzlib-1.2.13-hcfcfb64_4 None
  more-itertools     conda-forge/noarch::more-itertools-9.0.0-pyhd8ed1ab_0 None
  netaddr            conda-forge/noarch::netaddr-0.7.19-py_0 None
  ntlm-auth          conda-forge/noarch::ntlm-auth-1.5.0-pyh9f0ad1d_0 None
  openssl            conda-forge/win-64::openssl-3.0.5-hcfcfb64_2 None
  pip                conda-forge/noarch::pip-22.3-pyhd8ed1ab_0 None
  psutil             conda-forge/win-64::psutil-5.9.3-py310h8d17308_0 None
  px-proxy           conda-forge/win-64::px-proxy-20220127-py310h5588dad_0 None
  python             conda-forge/win-64::python-3.10.6-hcf16a7b_0_cpython None
  python_abi         conda-forge/win-64::python_abi-3.10-2_cp310 None
  pywin32            conda-forge/win-64::pywin32-303-py310he2412df_0 None
  pywin32-ctypes     conda-forge/win-64::pywin32-ctypes-0.2.0-py310h5588dad_1005 None
  setuptools         conda-forge/noarch::setuptools-65.5.0-pyhd8ed1ab_0 None
  tk                 conda-forge/win-64::tk-8.6.12-h8ffe710_0 None
  tzdata             conda-forge/noarch::tzdata-2022e-h191b570_0 None
  ucrt               conda-forge/win-64::ucrt-10.0.22621.0-h57928b3_0 None
  vc                 conda-forge/win-64::vc-14.3-h3d8a991_9 None
  vs2015_runtime     conda-forge/win-64::vs2015_runtime-14.32.31332-h1d6e394_9 None
  wheel              conda-forge/noarch::wheel-0.37.1-pyhd8ed1ab_0 None
  winkerberos        conda-forge/win-64::winkerberos-0.9.0-py310h5588dad_0 None
  xz                 conda-forge/win-64::xz-5.2.6-h8d14728_0 None


Proceed ([y]/n)?
```

I thought may #12 could fix, but no luck. May we should [mark those version with dates as broken](https://conda-forge.org/docs/orga/guidelines.html#fixing-broken-packages)? Or do you have another solution/recommendation @fcollonval?

### Installed packages

```shell
-
```

### Environment info

```shell
-
```

**Comment by fcollonval** [comment]
Mmm the only way without going to the broken path is actually to use a date version base. The trouble is that conda is considering the date as the major version.

It will be faster to handle by our-self to move to a date version base for conda. We should probably update the README to display the matching.

**Comment by m-rossi** [comment]
Not a good solution IMO, we should stick to the version numbering of the source repository. What was the reason to change to date based numbering?

**Comment by genotrance** [comment]
I can go ahead and delete those date releases - they were interim pre-releases (4 of them several years ago) before I abandoned the scheme. All their updates are present in subsequent releases.

I can see it is a nuisance for such purposes and am happy to take them down if it makes life easier. Please let me know if I should do so.

**Comment by m-rossi** [comment]
May instead of deleting them you could set them as a pre-release (as they are)? That is possible if you edit the release on github.

@fcollonval do you know if it is possible to move packages to a `rc`/`beta` channel later?

**Comment by fcollonval** [comment]
> do you know if it is possible to move packages to a `rc`/`beta` channel later?

Unfortunately no.

It seems we have only one solution according to [fixing broken package documentation](https://conda-forge.org/docs/maintainer/updating_pkgs.html#removing-broken-packages). As updating the repo data is always preserving the version, we should flag the package as broken. Could you take care of opening the appropriate PR @m-rossi ?

**Comment by m-rossi** [comment]
> Could you take care of opening the appropriate PR @m-rossi ?

Will do later today.

@genotrance Can you mark those releases with date-based-versions as prereleases on github?

**Comment by m-rossi** [comment]
It's now working as expected, thanks everyone!

**Comment by genotrance** [comment]
> @genotrance Can you mark those releases with date-based-versions as prereleases on github?

Those are already all pre-releases. I don't intend using that scheme anymore so we should be good going forward as well. Thanks!

**Comment by fcollonval** [comment]
Thanks a lot @m-rossi for taking care of that
